abstract class AppStates {}
class InitialAppState extends AppStates{}
class BottomNavBarState extends AppStates{}
class ChangeIconBottomNavBarState extends AppStates{}
class OnCreateDataAppState extends AppStates{}
class InsertDataAppState extends AppStates{}
class GetDataAppState extends AppStates{}
class LoadingGetDataAppState extends AppStates{}
class UbdateDataAppState extends AppStates{}
class DeleteDataAppState extends AppStates{}